### ISSUE TITLE
re-arrange layout

### ISSUE THREAD

**Issue by thcasey3** [ylin00/odnplab#8]
The page should open with the tools tab already there on the left. The order of components should go most to least important, top to bottom:

- Get file with Run button directly underneath on top,
- Then Spin concentration
- Then radiobuttons to select tethered or free,
- Then T1,0(0),
- *(this is as far as most of the users will need to go)
- Then T1 interpolation method,
- Then Magnetic field,
- Finally the slider to adjust integration width (this can be very useful but for consistency sticking with the default is advised so this should be de-emphasized)

**Comment by ylin00** [comment]
All bullet points have been resolved in v1.2
